name: Noetic

on:
  push:
  pull_request:
  schedule:
    # Run every Friday at 6:30 am to detect breaking APIs
    - cron: '30 6 * * 5'


jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
